### PR TITLE
First Commit of The Summer, left a note in txt file

### PR DESCRIPTION
**Pull request by CFdefense**
### Pull Request Created

Alt text

### CODE REVIEW

**Review by profphip — APPROVED** [review]
Hey Christian! The way I got my internship was by walking into the joint study program director's office and asking to join the joint study. I couldn't join the joint study because I played softball, so the director forwarded me some internship applications for IBM. The current joint study program director is Christy Schroeder and her office is in Hancock (I think 3rd floor). I'd suggest sending her an email asking to meet up with her to talk about internship opportunities for this upcoming summer. You can tell her I sent you her way. Bring your resume and a cover letter along with you just in case. Application season is coming up soon, so I'd meet with her sooner rather than later.

If you end up applying for an internship, you will likely have to complete hackerrank tests: https://www.hackerrank.com/  You might be able to find some practice problems on the site. There will be 3 problems and you'll have 3 hours to complete them. Then there will be 2 interviews that follow: one technical interview and one personable interview.

If you decide to go down this route, let me know, and I'd be happy to tell you more about the interview process, what it is like interning at IBM, etc.

**Comment by profphip** [comment]
You can go ahead and merge your changes and close this PR. Since you already worked on lab 2, make sure to git pull (or git fetch, git merge) your main branch into your lab-2 branch, then push your lab-2 branch. This way, you avoid merge conflicts.

**Comment by CFdefense** [comment]
Sounds good!

I will look to meet with Christy asap. We had a great conversation last
year and she ended up offering me joint study however I had to decline due
to competitive offers. I hope she doesn’t shun me out the door haha.

Thanks for all the advice!
Christian

**Comment by CFdefense** [comment]
Merging and closing

**Pull request merged**
