### PR TITLE
Being a windows user I had a lot of trouble with this

### PR DESCRIPTION
**Pull request by CFdefense**
Had a ton of issues with primarily ensuring that the environment was isolated and that the packages weren't installed globally. I did this by using "virtualenv .env", activating my environment, and then running "pip install <package-name>" for each package. This approach seemed to install the environment packages within the environment and then upon deactivating I would not see them within my global files.

Alt text

### CODE REVIEW

**Comment by CFdefense** [comment]
Yes I believe this was the solution which worked best, also I had to be in
the right directories of course for each step. If packages were installed
in the wrong place they had to be manually deleted one by one, unless there
exists some easier way I didn’t know about.

**Comment by CFdefense** [comment]
Another quick thing, I had to go and install python, and disable its
installers in “Manage App Execution Aliases.” Otherwise I would get python
not found when running any commands.

I don’t know why that text is now big haha.

Thanks,
Christian

**Comment by profphip** [comment]
Yeah - I'm learning quickly that Windows users have to install everything. I'll make sure that is added to labs going forward. Thanks for all your feedback!

I'm going to leave this PR open for now because this is a week #3 lab and I don't want to confuse anyone. Once I open the assignment, just be sure to paste this PR link there. Good work!

**Comment by CFdefense** [comment]
Sounds good, thanks!

**Comment by profphip** [comment]
Good work! Since this is based on the old (crappy) instructions, you'll have an extra venv directory in your labs folder. Feel free to rearrange that as you see fit (if at all). You can go ahead and close this PR and merge your changes

**Review by profphip — APPROVED** [review]

**Comment by CFdefense** [comment]
Awesome, thank you so much!

**Pull request merged**
